spring:
  datasource:
    url: jdbc:mysql://localhost:3306/turingblog?serverTimezone=UTC&&characterEncoding=utf-8&useSSL=false
    username: root
    password: huliwei1
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#原来在MybatisConfig配置的设置在导入依赖后,可以直接在properties或yaml配置
mybatis:
  type-aliases-package: com.turingcoourt
  configuration.map-underscore-to-camel-case: true
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
