spring:
  servlet:
    multipart:
      #配置文件最大限制
      max-file-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/turingblog?serverTimezone=UTC&&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


#原来在MybatisConfig配置的设置在导入依赖后,可以直接在properties或yaml配置
mybatis:
  type-aliases-package: com.turingcourt
  configuration.map-underscore-to-camel-case: true
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
